require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']

Metrics/AbcSize:
  CountRepeatedAttributes: false
