require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'heredoc', 'method_call', 'hash']

Metrics/AbcSize:
  CountRepeatedAttributes: false

RSpec/MessageSpies:
  EnforcedStyle: receive

# RSpec/NestedGroups:
#   MaxNesting: 4

# RSpec/MultipleMemoizedHelpers:
#   Max: 6
