require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false
